### ISSUE TITLE
Spawning server-like processes prevents tests from completing

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/test_process#31]
Given the following test configuration:

```dart
// test/server_test.dart

import 'package:http/http.dart';
import 'package:test/test.dart';
import 'package:test_process/test_process.dart';

void main() {
  final port = '8080';
  final host = 'http://0.0.0.0:$port';
  late TestProcess p;

  setUp(() async {
    p = await TestProcess.start(
      'dart',
      ['run', 'bin/server.dart'],
      environment: {'PORT': port},
    );
    await Future.delayed(const Duration(seconds: 2));
  });

  tearDown(() => print('teardown!');

  test('Root', () async {
    final response = await get(Uri.parse(host + '/'));
    expect(response.statusCode, 200);
    expect(response.body, 'Hello, World!\n');
  });
}
```

```dart
// bin/server.dart
import 'dart:io';

import 'package:shelf/shelf.dart';
import 'package:shelf/shelf_io.dart';
import 'package:shelf_router/shelf_router.dart';

// Configure routes.
final _router = Router()
  ..get('/', _rootHandler)
  ..get('/echo/<message>', _echoHandler);

Response _rootHandler(Request req) {
  print("responding hello world");
  return Response.ok('Hello, World!\n');
}

Response _echoHandler(Request request) {
  print("Echo handler");
  final message = params(request, 'message');
  return Response.ok('$message\n');
}

void main(List<String> args) async {
  // Use any available host or container IP (usually `0.0.0.0`).
  final ip = InternetAddress.anyIPv4;

  // Configure a pipeline that logs requests.
  final _handler = Pipeline().addMiddleware(logRequests()).addHandler(_router);

  // For running in containers, we respect the PORT environment variable.
  final port = int.parse(Platform.environment['PORT'] ?? '8080');
  final server = await serve(_handler, ip, port);
  print('Server listening on port ${server.port}');
}

```

The test will not complete and `tearDown` is not invoked. It looks like there's 3 stream-related ports that are being held open by `TestProcess`, all of which appear to be related to the `stdout` and `stderr` subscriptions.

At the very least, we should document that `process.kill()` needs to be called within the test.

**Comment by jakemac53** [comment]
This package does have code that should automatically set up a `tearDown` and kill the process.

It sounds like the issue is for some reason we are never even getting to `tearDown`? Not sure what would cause it but I can take a quick look.

**Comment by jakemac53** [comment]
Ok, I tracked this down, although I am not sure if it is intended behavior or what exactly. It is because of [this line](https://github.com/dart-lang/test_process/blob/master/lib/test_process.dart#L122).

That sets up an _async matcher_ which never completes until the process exits, and so we won't invoke `tearDown` because the test still has pending async matchers.

I think we should consider just removing this expectation? cc @natebosch for thoughts.

**Comment by natebosch** [comment]
Hmm, this implies that we've never relied on the implicit `tearDown`...

https://github.com/dart-lang/test_process/blob/52732de0571919b04f3bc6a0ed613ac7d7139d5c/lib/test_process.dart#L148

I think it should be fine to drop that expectation. I'm very surprised we've never seen this come up before.

**Comment by natebosch** [comment]
Or, can you hit the teardown if the test times out?

Maybe we just need to document that any process started during a test needs to end during that test?

**Comment by jakemac53** [comment]
> Or, can you hit the teardown if the test times out?

Yes, it is still hit during a timeout so it cleans things up.

> Maybe we just need to document that any process started during a test needs to end during that test?

This is another option... I don't feel super strongly either way.

**Comment by evanweible-wf** [comment]
I just ran into this today when trying to test a long-running server-like process. I'd vote for either removing that expectation or making it configurable, because unfortunately it seems to cause this issue even if you try to kill the process as a part of the test (which you might reasonably do when trying to test a server-like process). Calling `process.kill()` on a TestProcess instance within a test still results in an error due to a failure after the test has completed.
